default/app.yaml:


runtime: go118
env: flex

service: default

handlers:
  - url: /.*
    script: auto

liveness_check:
  path: /
  initial_delay: 10s
  timeout: 5s

readiness_check:
  path: /
  initial_delay: 10s
  timeout: 5s

resources:
  cpu: 1
  memory: 1G

instances: 1


