steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/movieproyectapi', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/movieproyectapi']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--image-url=gcr.io/$PROJECT_ID/movieproyectapi', '--version=v1']

substitutions:
  _PROJECT_ID: encoded-102001

options:
  logging: CLOUD_LOGGING_ONLY
